In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('blkjckhands.csv', sep=',')
df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,0,Player1,7,10,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
1,1,Player2,10,9,0,0,0,19,10,8,...,0,0,18,nowin,Win,Plwin,Beat,20,0,19
2,2,Player3,9,8,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
3,3,Player4,2,10,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
4,4,Player5,10,2,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1,Player2,10,7,0,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,17
899996,2,Player3,6,1,10,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,7
899997,3,Player4,4,2,9,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,6
899998,4,Player5,9,10,0,0,0,19,3,9,...,2,0,18,nowin,Win,Plwin,Beat,20,0,19
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [2]:
invalid_data = df.loc[(df['card3'] == 0) & ((df['card4'] != 0) | (df['card5'] != 0))]
invalid_data_index = df.loc[(df['card3'] == 0) & ((df['card4'] != 0) | (df['card5'] != 0))].index
invalid_data_index

Int64Index([     3,      4,     18,     19,     20,     23,     24,     28,
                29,     30,
            ...
            899960, 899961, 899963, 899964, 899968, 899969, 899976, 899977,
            899979, 899989],
           dtype='int64', length=226004)

In [3]:
df.drop(invalid_data_index)

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,0,Player1,7,10,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
1,1,Player2,10,9,0,0,0,19,10,8,...,0,0,18,nowin,Win,Plwin,Beat,20,0,19
2,2,Player3,9,8,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
5,5,Player6,6,1,8,10,0,25,10,8,...,0,0,18,nowin,Loss,Bust,PlBust,0,10,7
6,0,Player1,10,4,0,0,0,14,4,4,...,10,0,23,nowin,Win,DlBust,Bust,20,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1,Player2,10,7,0,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,17
899996,2,Player3,6,1,10,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,7
899997,3,Player4,4,2,9,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,6
899998,4,Player5,9,10,0,0,0,19,3,9,...,2,0,18,nowin,Win,Plwin,Beat,20,0,19
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [4]:
df.groupby(['PlayerNo'])['plwinamt'].sum()

PlayerNo
Player1    1460415
Player2    1458320
Player3    1455900
Player4    1458430
Player5    1456025
Player6    1462085
Name: plwinamt, dtype: int64

In [5]:
df.groupby(['PlayerNo'])['plwinamt'].sum().idxmax()

'Player6'

In [6]:
ply6_df = df.loc[df['PlayerNo'] == 'Player6']
ply6_df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
5,5,Player6,6,1,8,10,0,25,10,8,...,0,0,18,nowin,Loss,Bust,PlBust,0,10,7
11,5,Player6,3,5,2,4,0,14,4,4,...,10,0,23,nowin,Win,DlBust,Bust,20,0,8
17,5,Player6,9,5,0,0,0,14,4,6,...,10,0,26,nowin,Win,DlBust,Bust,20,0,14
23,5,Player6,4,8,0,10,0,22,10,8,...,0,0,18,nowin,Loss,Bust,PlBust,0,10,12
29,5,Player6,9,3,0,6,0,18,8,7,...,0,0,19,nowin,Loss,Beat,Dlwin,0,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899975,5,Player6,2,3,8,0,0,13,6,9,...,0,0,19,nowin,Loss,Beat,Dlwin,0,10,5
899981,5,Player6,9,10,0,0,0,19,11,10,...,0,0,21,nowin,Loss,Beat,Dlwin,0,10,19
899987,5,Player6,4,5,10,0,0,19,6,10,...,0,0,26,nowin,Win,DlBust,Bust,20,0,9
899993,5,Player6,8,3,10,0,0,21,10,2,...,0,0,21,nowin,Push,Push,Push,10,0,11
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [7]:
ply_test = ply6_df.loc[:,['card1','card2','card3','card4','card5']]

In [8]:
dl_test = ply6_df.loc[:,['dealcard1','dealcard2','dealcard3','dealcard4','dealcard5']]

In [9]:
ply_test.to_numpy()

array([[ 6,  1,  8, 10,  0],
       [ 3,  5,  2,  4,  0],
       [ 9,  5,  0,  0,  0],
       ...,
       [ 4,  5, 10,  0,  0],
       [ 8,  3, 10,  0,  0],
       [ 5, 10,  0,  0,  0]])

In [13]:
df.loc[(df['plwinamt'] == 25) & (df['card3'] != 0)]

Empty DataFrame
Columns: [Unnamed: 0, PlayerNo, card1, card2, card3, card4, card5, sumofcards, dealcard1, dealcard2, dealcard3, dealcard4, dealcard5, sumofdeal, blkjck, winloss, plybustbeat, dlbustbeat, plwinamt, dlwinamt, ply2cardsum]
Index: []

[0 rows x 21 columns]