In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('blkjckhands.csv', sep=',')
df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,0,Player1,7,10,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
1,1,Player2,10,9,0,0,0,19,10,8,...,0,0,18,nowin,Win,Plwin,Beat,20,0,19
2,2,Player3,9,8,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
3,3,Player4,2,10,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
4,4,Player5,10,2,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1,Player2,10,7,0,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,17
899996,2,Player3,6,1,10,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,7
899997,3,Player4,4,2,9,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,6
899998,4,Player5,9,10,0,0,0,19,3,9,...,2,0,18,nowin,Win,Plwin,Beat,20,0,19
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [2]:
df.describe()

,Unnamed: 0,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,dealcard3,dealcard4,dealcard5,sumofdeal,plwinamt,dlwinamt,ply2cardsum
count,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000,900000.000000
mean,2.500000,7.126259,7.089927,1.955088,2.336462,0.389787,18.897522,7.170380,7.129867,4.391293,1.380733,0.226433,20.298707,9.723528,4.775789,14.216186
std,1.707826,2.994719,3.008032,3.531830,3.657284,1.730740,3.210611,2.981575,2.990306,4.080103,3.038298,1.334263,2.556207,9.789798,4.994973,4.429873
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,8.000000,1.000000,1.000000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,2.000000
25%,1.000000,5.000000,4.000000,0.000000,0.000000,0.000000,17.000000,5.000000,5.000000,0.000000,0.000000,0.000000,18.000000,0.000000,0.000000,12.000000
50%,2.500000,8.000000,8.000000,0.000000,0.000000,0.000000,19.000000,8.000000,8.000000,4.000000,0.000000,0.000000,20.000000,10.000000,0.000000,14.000000
75%,4.000000,10.000000,10.000000,2.000000,4.000000,0.000000,21.000000,10.000000,10.000000,9.000000,0.000000,0.000000,22.000000,20.000000,10.000000,18.000000
max,5.000000,11.000000,11.000000,11.000000,10.000000,10.000000,26.000000,11.000000,11.000000,11.000000,10.000000,10.000000,26.000000,25.000000,10.000000,21.000000

In [26]:
df['valid?'] = df.apply(lambda x: 0 if df['card3']== 0 and (df['card4']!=0 or df['card5']!=0) else 1)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [3]:
df.groupby(['PlayerNo'])['plwinamt'].sum()

PlayerNo
Player1    1460415
Player2    1458320
Player3    1455900
Player4    1458430
Player5    1456025
Player6    1462085
Name: plwinamt, dtype: int64

In [4]:
sp = df.loc[df['plwinamt'] == 10]
sp

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
27,3,Player4,2,9,8,0,0,19,8,7,...,0,0,19,nowin,Push,Push,Push,10,0,11
49,1,Player2,3,2,5,10,0,20,10,10,...,0,0,20,nowin,Push,Push,Push,10,0,5
51,3,Player4,5,9,0,6,0,20,10,10,...,0,0,20,nowin,Push,Push,Push,10,0,14
65,5,Player6,5,6,8,0,0,19,10,5,...,0,0,19,nowin,Push,Push,Push,10,0,11
70,4,Player5,11,10,0,0,0,21,10,11,...,0,0,21,Win,Push,Push,Push,10,0,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899969,5,Player6,10,4,0,3,0,17,11,6,...,0,0,17,nowin,Push,Push,Push,10,0,14
899972,2,Player3,4,5,10,0,0,19,6,9,...,0,0,19,nowin,Push,Push,Push,10,0,9
899989,1,Player2,3,10,0,8,0,21,10,2,...,0,0,21,nowin,Push,Push,Push,10,0,13
899991,3,Player4,9,2,10,0,0,21,10,2,...,0,0,21,nowin,Push,Push,Push,10,0,11
899993,5,Player6,8,3,10,0,0,21,10,2,...,0,0,21,nowin,Push,Push,Push,10,0,11

In [5]:
df.groupby(['PlayerNo'])['plwinamt'].sum().idxmax()

'Player6'

In [6]:
ply6_df = df.loc[df['PlayerNo'] == 'Player6']
ply6_df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
5,5,Player6,6,1,8,10,0,25,10,8,...,0,0,18,nowin,Loss,Bust,PlBust,0,10,7
11,5,Player6,3,5,2,4,0,14,4,4,...,10,0,23,nowin,Win,DlBust,Bust,20,0,8
17,5,Player6,9,5,0,0,0,14,4,6,...,10,0,26,nowin,Win,DlBust,Bust,20,0,14
23,5,Player6,4,8,0,10,0,22,10,8,...,0,0,18,nowin,Loss,Bust,PlBust,0,10,12
29,5,Player6,9,3,0,6,0,18,8,7,...,0,0,19,nowin,Loss,Beat,Dlwin,0,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899975,5,Player6,2,3,8,0,0,13,6,9,...,0,0,19,nowin,Loss,Beat,Dlwin,0,10,5
899981,5,Player6,9,10,0,0,0,19,11,10,...,0,0,21,nowin,Loss,Beat,Dlwin,0,10,19
899987,5,Player6,4,5,10,0,0,19,6,10,...,0,0,26,nowin,Win,DlBust,Bust,20,0,9
899993,5,Player6,8,3,10,0,0,21,10,2,...,0,0,21,nowin,Push,Push,Push,10,0,11
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [9]:
ply_test = ply6_df.loc[:,['card1','card2','card3','card4','card5']]

In [10]:
dl_test = ply6_df.loc[:,['dealcard1','dealcard2','dealcard3','dealcard4','dealcard5']]