In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('blkjckhands.csv', sep=',')
df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,0,Player1,7,10,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
1,1,Player2,10,9,0,0,0,19,10,8,...,0,0,18,nowin,Win,Plwin,Beat,20,0,19
2,2,Player3,9,8,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
3,3,Player4,2,10,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
4,4,Player5,10,2,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1,Player2,10,7,0,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,17
899996,2,Player3,6,1,10,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,7
899997,3,Player4,4,2,9,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,6
899998,4,Player5,9,10,0,0,0,19,3,9,...,2,0,18,nowin,Win,Plwin,Beat,20,0,19
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [2]:
#find the data which does not follow the game rule
invalid_data = df.loc[(df['card3'] == 0) & ((df['card4'] != 0) | (df['card5'] != 0))]
invalid_data_index = df.loc[(df['card3'] == 0) & ((df['card4'] != 0) | (df['card5'] != 0))].index
invalid_data_index

Int64Index([     3,      4,     18,     19,     20,     23,     24,     28,
                29,     30,
            ...
            899960, 899961, 899963, 899964, 899968, 899969, 899976, 899977,
            899979, 899989],
           dtype='int64', length=226004)

In [3]:
#remove invalid data
df = df.drop(invalid_data_index)

In [4]:
df=df.replace({'winloss': {'Win': 1, 'Loss': -1, 'Push':0}})

In [5]:
df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,0,Player1,7,10,0,0,0,17,10,8,...,0,0,18,nowin,-1,Beat,Dlwin,0,10,17
1,1,Player2,10,9,0,0,0,19,10,8,...,0,0,18,nowin,1,Plwin,Beat,20,0,19
2,2,Player3,9,8,0,0,0,17,10,8,...,0,0,18,nowin,-1,Beat,Dlwin,0,10,17
5,5,Player6,6,1,8,10,0,25,10,8,...,0,0,18,nowin,-1,Bust,PlBust,0,10,7
6,0,Player1,10,4,0,0,0,14,4,4,...,10,0,23,nowin,1,DlBust,Bust,20,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1,Player2,10,7,0,0,0,17,3,9,...,2,0,18,nowin,-1,Beat,Dlwin,0,10,17
899996,2,Player3,6,1,10,0,0,17,3,9,...,2,0,18,nowin,-1,Beat,Dlwin,0,10,7
899997,3,Player4,4,2,9,0,0,15,3,9,...,2,0,18,nowin,-1,Beat,Dlwin,0,10,6
899998,4,Player5,9,10,0,0,0,19,3,9,...,2,0,18,nowin,1,Plwin,Beat,20,0,19
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,-1,Beat,Dlwin,0,10,15

In [6]:
df.groupby(['PlayerNo']).sum()

,Unnamed: 0,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,dealcard3,dealcard4,dealcard5,sumofdeal,winloss,plwinamt,dlwinamt,ply2cardsum
PlayerNo,,,,,,,,,,,,,,,,,
Player1,0,809438,802808,294795,104023,19164,2030228,742780,797296,540834,176140,29407,2286457,9804,1251485,454670,1612246
Player2,112389,811123,805398,292005,104432,20620,2033578,744880,799148,540916,175177,29506,2289627,9287,1248690,458430,1616521
Player3,224252,808436,801691,292616,105238,19190,2027171,743208,796861,539541,175742,29503,2284855,9049,1243290,459160,1610127
Player4,337203,809808,805147,293610,104783,19393,2032741,745567,798614,541014,175124,29538,2289857,9317,1248880,459080,1614955
Player5,449228,810484,805738,291397,103708,19767,2031094,744090,798312,540503,175927,29421,2288253,9069,1245355,458320,1616222
Player6,562900,812319,806623,295156,104262,19410,2037770,746798,800350,540736,175688,29603,2293175,9235,1249795,458350,1618942

In [7]:
df.groupby(['PlayerNo'])['winloss'].count()

PlayerNo
Player1    112193
Player2    112389
Player3    112126
Player4    112401
Player5    112307
Player6    112580
Name: winloss, dtype: int64

In [8]:
win_rate = df.groupby(['PlayerNo'])['winloss'].sum()/df.groupby(['PlayerNo'])['winloss'].count()
win_rate

PlayerNo
Player1    0.087385
Player2    0.082633
Player3    0.080704
Player4    0.082891
Player5    0.080752
Player6    0.082031
Name: winloss, dtype: float64

In [9]:
#find the win most player
win_rate.idxmax()

'Player1'

In [10]:
ply_df = df.loc[df['PlayerNo'] == 'Player1']
ply_df.drop(columns='Unnamed: 0')

,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,dealcard3,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,Player1,7,10,0,0,0,17,10,8,0,0,0,18,nowin,-1,Beat,Dlwin,0,10,17
6,Player1,10,4,0,0,0,14,4,4,5,10,0,23,nowin,1,DlBust,Bust,20,0,14
12,Player1,10,2,0,0,0,12,4,6,6,10,0,26,nowin,1,DlBust,Bust,20,0,12
36,Player1,5,9,0,0,0,14,6,3,6,8,0,23,nowin,1,DlBust,Bust,20,0,14
42,Player1,6,7,0,0,0,13,5,10,2,0,0,17,nowin,-1,Beat,Dlwin,0,10,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899940,Player1,10,10,0,0,0,20,11,10,0,0,0,21,nowin,-1,Beat,Dlwin,0,10,20
899970,Player1,10,10,0,0,0,20,6,9,4,0,0,19,nowin,1,Plwin,Beat,20,0,20
899982,Player1,10,11,0,0,0,21,6,10,10,0,0,26,Win,1,DlBust,Bust,25,0,21
899988,Player1,10,9,0,0,0,19,10,2,9,0,0,21,nowin,-1,Beat,Dlwin,0,10,19
899994,Player1,10,10,0,0,0,20,3,9,4,2,0,18,nowin,1,Plwin,Beat,20,0,20

In [12]:
ply_df.to_csv('kaggle_test_env.csv')